language: rust
osx_image: xcode10.2

git:
  submodules: true
  depth: 5

os:
  - osx

rust:
  - stable

cache: cargo

before_script:
  - sudo gem install xcpretty

script:
  # - xcodebuild test -scheme XiEditor | xcpretty -s && exit ${PIPESTATUS[0]}
  xcodebuild

before_deploy:
  - zip XiEditor.zip /Users/travis/build/sadikovi/xi-mac/build/Release/XiEditor.app

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: XiEditor.zip
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
